name: 'Composite action to launch js minification'
description: 'Composite action to launch js minification'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      shell: bash
      run: npm ci
