name: 'Composite action to launch js minification'
description: 'Composite action to launch js minification'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      shell: bash
      run: npm install esbuild @babel/core @babel/preset-env
      
    - name: Minify JavaScript
      shell: bash
      run: |
        if [[ ${{ github.ref }} == "refs/heads/main" ]]; then
          echo "[INFO] ${{ github.workflow }}: script is enabled for this branch"
        elif [[ ${{ github.ref }} =~ ^(refs/heads/staging|refs/heads/release)-.*$ ]] && [[ $(git log --format=%B -n 1) =~ ^.*\[hotfix\].*$ ]]; then
          echo "[INFO] ${{ github.workflow }}: script is enabled for hotfixes"
        else
          echo "[INFO] ${{ github.workflow }}: script is disabled for this branch (script is enabled for master and [hotfix] commits)" && exit 0
        fi
    - uses: actions/checkout@v4
    - name: Commit changes
      run: |
        git config user.name 'GitHub Actions'
        git config user.email 'actions@github.com'
        git add .
        git diff-index --quiet --cached HEAD -- || git commit -m "Minification of JS files"
        git push origin HEAD:${{ github.ref }}
