name: 'Composite action to prepare automated tests'
description: 'Composite action to prepare automated tests.'

runs:
  using: "composite"
  steps:
    - name: Log in to ghcr.io (GitHub Container Registry (v2))
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.docker_registry }}
        username: ${{ inputs.docker_registry_username }}
        password: ${{ inputs.docker_registry_password }}

    - name: Build the stack
      shell: bash
      run: cd ci-tests && docker-compose -f ${{ inputs.docker_compose_filename }} up -d

    - name: Install composer packages
      uses: php-actions/composer@v6

    - name: Wait for mySQL to be available
      shell: bash
      run: cd ci-tests && sh mysqlAvailable.sh
